```
title: "EDF 5400 Labs:  Frequently Asked Questions"
```


# Frequently Asked Questions (by me as I review the labs)

As well as frequently missed points.

## Part One

* *Which Researchers?*  A statement like "Researchers have found that..." begs the question of which researchers.  Much better to write "Dewey, Cheetum, and Howe (1999) found that ..."

* *To which population does the research question apply?*  Note that the Prevatt et al. (2015) study only works with college students (as opposed to elementary and secondardy students in much of the ADHD literature).  Also, for the relationship between ADHD symptoms and Anxiety/Panic, only the ADHD students filled out the symptom questionnaires.

* *What does GADD, PAG, genaxa, paa mean?*  Replace these abbreviations with full names.  The best way to do this is by entering the full names in the "Variables" view of SPSS ([Entering Labels](https://myweb.fsu.edu/ralmond/ADHDLabs/lab_dataEntry.html#editing-the-metadata)).  SPSS will then use these in graphs in tables.

* *Is 1 male or female?*  Setting the "Value Labels" produces more readable tables and graphs.  ([Entering Value Labels](https://myweb.fsu.edu/ralmond/ADHDLabs/lab_dataEntry.html#setting-value-labels))

* *Which variables are you using?*  No need to waste time describing variables which are not in your analyses.

* *Are there out of range values?*  All of the measures are positive.  If you see negative values, that is an indication that the missing data were not properly cleaned.  Also, the maximum `GADD` score is 6 and the maximum `PAG` score is 5; the maximum value for both `hyper` and `innatt` is 27.  These are probably typos, so fix them.  ([Coding Missing Values](https://myweb.fsu.edu/ralmond/ADHDLabs/lab_dataEntry.html#coding-missing-values))

## Part Two

* *How many digits do you need?*  My rule of thumb, is means get one more digit than the raw data and SDs get two.  Thus if `age` takes on integer values, `mean(age)` should be reported with 1 decimal and `sd(age)` with two.  [Adjusting digits in tables](https://myweb.fsu.edu/ralmond/ADHDLabs/TableStyle.html#digits)

* *Is this table in academic style?* The default SPSS tables, while not as disastrous from a graphic design perspective as earlier version of SPSS) are still not the usual APA/Academic style. [Making APA style tables in SPSS](https://myweb.fsu.edu/ralmond/ADHDLabs/TableStyle.html#apa-style)

* *Is this table laid out correctly?*  When making a table with more than two factors (e.g., measures, statistics and groups), SPSS often doesn't group them in such a way that the variables a reader wants to compare are next to each other.  Pivoting the table can help.  [Pivot Tables](https://myweb.fsu.edu/ralmond/ADHDLabs/TableStyle.html#table-layout)

* *Is this graph laid out correctly?*  When using paneled histograms, it is usually better to panel by rows, as that makes it easier to compare the distributions. [Paneling Histograms](https://myweb.fsu.edu/ralmond/ADHDLabs/lab_EDA.html#stacking-histograms)  Also, for scatterplots, put the variable being predicted, the $Y$-variable is put on the $y$-axis.  [Making Scatterplots](https://myweb.fsu.edu/ralmond/ADHDLabs/lab_regression.html#initial-analysis)

* *Are the labels on tables and graph human readable?*  If you are using cryptic names like `GADD` or `hyper` in the graph, then you need to set the variable labels.  If you have numbers instead of category labels, then you need to set the value labels.  You can also edit the table or graph directly, but getting the labels right in the variable view is easier.

* *Figure and Table Placement*

* *Figure and Table Captions*

*  *Do I need both histograms and boxplots?* The best way to answer
    this question is to think of your lab report as telling a story. Do
    the histograms and boxplots tell different stories? If yes, include
    them both (and explain in the text the interesting observations in
    both). If no, pick the one that tells the story the best and include
    only that one.



## Part Three

* *SPSS gave me a significance of .000, what should I do for the*
p*-value?*

Put down *p\<.001* (SPSS automatically rounds the *p-*value to three
digits, and so it must be smaller than that, but it is not impossible,
so the value is not zero).

:::{.callout-note}
Current versions of SPSS properly report the $p$-value, but this problem is still one to worry about.  Note that R will sometimes give you a p-value that looks like `7.619853e-24` (the `e-24`  means 24 zeros after the decimal point).  This should be repored at `p < .001`
:::


* *How do I pick which line of the t-test results to use?*

SPSS provides more information here than you need to report. First, look
at Levene's test (the first couple of columns which appear only in the
first row). Is it reasonable to assume that the variances are equal? If
so, use the first line of the table. If not, use the second line of the
table. Generally you do not need to report Levene's test, unless you
decided to use the unequal variance procedure because of it.

Another viable strategy is to ignore Levene's test, and always use the
second row. If the variances are approximately equal both rows are about
the same. If the variances are different, then the second row is the one
to use anyway.

:::{.callout-note}
tl:dr  Just use the last line.
:::

* *Why doesn't SPSS supply an effect size?*

I don't know, but if you wait for IBM to supply one, you won't get the
lab in on time. Haiyan Wu (with some cleanup by Zhongtian Liang) put
together an Excel spreadsheet which has the formula in it. This is
available at
[effectSize\_d.xls](http://myweb.fsu.edu/ralmond/effectSize_d.xls).

:::{.callout-note}
Hurrah!  IBM fixed this.  I recommend using Cohen's $d$.  Note that the value you want is in the second column.
:::


* *How come I got a different result from the one in Prevatt et al.
(2015)?*

Dr. Prevatt did the analysis for that paper a year or two before she
shared the data with us (it just takes that long to go through the
review processes). Therefore, do not expect the number you get to be
exactly the same as those found by Prevatt et al. (2015).

* *Have I done all of the required tests?*

You should have both a one-sample confidence interval and independent
(2-sample) *t*-test. Every time you do a test you need to report the
*t-*value, degrees of freedom, *p*-value and effect size. You should
have done the test with and without the graduate students and you should
have graphical support for all of your tests[@knuth84].

* *Which tables should I include?*


## Part Four


* *Use variable labels.* If you add text labels to your variables as
    you create them (you can do this in the transformation dialog) the
    plots and table will come out with more human readable labels.


* *Is XXX an outlier I should worry about?* Not every point that shows
    up on the extreme ends of the scatterplot is an outlier. The boxplot
    has a built-in test for outliers, so that is a good tool for double
    checking whether something you noted in the scatterplot is an
    outlier or not. If you suspect outliers, another test you can make
    is to rerun the regression excluding the potential outliers. To do
    this, use the command [D]{.underline}ata \> [S]{.underline}elect
    Cases... \[ALT+D S\] and select the "If..." option and write an
    expression that will exclude the outliers, e.g., "hyper \< 35". Then
    run the regression or correlation command again.

The slope and correlation should change a little bit, but not a lot. If
they do change a lot, then the outlier is worth mentioning. If they
don't you could give it a passing mention (e.g., "XXX thought to be an
outlier, but rerunning the regression with XXX excluded produced only a
small change in the correlation and slope."), but not more. However, if
the results change markedly, report both numbers (unless you have a
substantial reason for thinking the outlier doesn\'t belong in the
population). It is fairly common for students to go outlier crazy at
this point in time, don't fall into that trap.

*Here are some web sites that cover SPSS and regression that you may
find helpful:*

[[http://www.ats.ucla.edu/stat/spss/seminars/SPSSGraphics/spssgraph.htm]{.underline}](http://www.ats.ucla.edu/stat/spss/seminars/SPSSGraphics/spssgraph.htm)

[[http://core.ecu.edu/psyc/wuenschk/spss/corrregr-spss.doc]{.underline}](http://core.ecu.edu/psyc/wuenschk/spss/corrregr-spss.doc)

* * Which Tables should I include?*


## Final Lab

* *If I fix every single thing the TAs mark on my draft lab, will I get a
perfect score on the final?*

No. Often other mistakes become apparent once the first mistakes are
fixed. Sometimes we will miss things on the first round and pick them up
on the second. This is life in the research world and the same thing
often happens with research papers and grant proposals. Get used to it.
