---
title: "EDF 5400 ADHD Labs:  Final Report
---

# Final Report

Pretend that you are analyzing these results and submitting them as a
paper to a journal. You will need to follow general APA style. Your
report should have the following sections (you can use different names,
but the contents should be there).

1.  Introduction \-\-- A brief statement of the general problem you are
    solving and why somebody might care. \[I'm doing this because it's a
    homework assignment doesn't count; be creative here.\]

2.  Research Question/Hypothesis \-\-- A brief statement of what
    question you are trying to answer and what you expect to find
    according to your theory. This is the *scientific hypothesis* and
    not the null hypothesis. Note that this lab has three research
    questions: corresponding to Sections 3, 4 and 5.

3.  Data \-\-- A brief description of the data. What was the population
    and how the data were sampled. \[This should not be a click-by-click
    description of what you did in SPSS, but rather make it sound like a
    real scientific study.\] Don't forget to cite your source!

4.  Analysis \-\-- Some descriptive statistics about the data followed
    by the results of the formal hypothesis test. You should include a
    graph and table to highlight what you observed. You should include a
    test statistic, p-value and effect size. APA style contains
    recommended method for reporting the results of common tests. Check
    the APA style guide for the labs on Blackboard.

5.  Conclusions \-\-- Describe what the statistical results mean in
    terms of the scientific problem posed at the beginning of the
    report. A significant difference is not you conclusion, but rather
    evidence that supports your conclusion. Speculate about whether or
    not you can generalize from the conclusions. Note that the data are
    NOT a random sample. How does that limit the conclusions?

As before, you will need to turn in a draft, which will be marked up,
followed by a final paper. Check blackboard for the due date. The final
is due one week after the initial drafts are marked.

## Pointers on Style

Don't use too many digits in your tables or text. SPSS will cheerfully
compute means to 6 decimal places even if the original data only has one
or two. Generally speaking, a mean should have one more decimal place
than the original data and a standard deviation should have one more
decimal place than the mean.

When the experiment compares two different genders special care is
needed.[^3] (My intent is not to preach political correctness here, but
rather to make you aware of the general rules for academic writing about
sensitive topics, so that your paper won't get bounced by a politically
correct editor.) When speaking about the two different genders use
equivalent terms, e.g., "men" and "women", "male" and "female", or
"boys" and "girls". Don't use terms that might be regarded as unequal,
e.g., "men" and "girls." Make sure that you don't imply that difference
in speed makes men better than women, e.g., "The study found that men
were better *runners* than women," rather than just "The study found
that men were better than women."[^4] Bear in mind that your subjects
are human beings with dignity and worth beyond the few numbers we have
gathered about them. That should keep you out of trouble. (Similar rules
apply when writing about racial differences or persons with
disabilities.)

Finally, go back to lab one and the style guide and review the pointers
on making graphs and naming variables. All of these rules will still
apply.

Jiwon (Alice) Nam, a TA for 5400 in Fall of 2010, put together a brief
guide to APA style. Take a look at this. You don't need to follow APA
style strictly, but you must have all of the five elements described in
Section 8 and they must be easy for the reader to find to get full style
points.

[^3]: This is no longer relevant for the current version of the lab, but
    it's a generally useful tip. However, see the footnote on page one
    about students with disabilities.

[^4]: A previous version of this lab used a data set with running times

<!-- Update the comments on pronouns to link to APA style blog -->
